### ISSUE TITLE
Update of the {rule name} ESLint rule

### ISSUE THREAD

**Issue by cermakjiri** [AckeeCZ/eslint-config-ackee#1]
# [rule-name](https://eslint.org/docs/rules/rule-name)

### What is the current rule state?

{your response}

### Why have you decided to change it?

{your response}

### What benefit will it bring to the rest of the team?

{your response}

Let's vote as follows:

- :thumbsup: for `error` value
- :handshake: to diminish to `warn`
- :thumbsdown: to turn off the rule

**Comment by horaklukas** [comment]
Why did you close it? 😄

**Comment by cermakjiri** [comment]
I've just wanted to test the template 😄
