### ISSUE TITLE
Update of the no-console ESLint rule

### ISSUE THREAD

**Issue by horaklukas** [AckeeCZ/eslint-config-ackee#3]
# [no-console](https://eslint.org/docs/rules/no-console)

### What is the current rule state?

It's set to produce error when `console` statement is present.

### Why have you decided to change it?

I suggest to diminish it to warning.

### What benefit will it bring to the rest of the team?

Althought we want to check presence of console statements left from development, it's not rare to use these statements in production code, so my opinion is that setting it to `error` is unnecessary too strict.

Let's vote as follows:

- :thumbsup: for `error` value
- 👀 : to diminish to `warn`
- :thumbsdown: to turn off the rule

**Comment by smoliji** [comment]
My opinion about this is that console should not be used at all by it self, as is it cannot be configured on one place and scattered console logs are just a mess.

If logging is needed in the application code, there should be a proper logger.

Even specifying a `const logger = console` and using the `logger` (which avoids the rule) is better than using console directly, imho.

**Comment by grissius** [comment]
Agree with @smoliji. There is no place for console in any but development/debug stage (except for very special cases, which should be handled by explicit ignore, the same way like dangerously setting HTML, which is also an error in Airbnb rules for React, I believe) and it should be an error.

> It's not rare to use these statements in production code

I would argue it is, or should be rare. But I am willing to change my mind (and vote :smiley_cat:), if specific, reasonable cases of usage are presented.

The only annoying thing I encountered about it was when the development server for FE app was also linting and would not compile with lint errors. That is an issue with requesting lint valid code for compilation, not with the rules themselves.

**Comment by horaklukas** [comment]
Ok, I accept that creating `logger.js` containing few simple statements you described is better approach of using native console (when necessary in early stages) and you changed my mind about this rule 🙂 

There are still cases when adopting 3rd party code (eg. Abibuch, ZK) where console.logs are yield of other programmers. But these files (although modified) should been probably excluded from linting.
